# Generated by Django 2.1 on 2018-09-08 19:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homesiteusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default=None, max_length=250)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homesiteusers.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('ordinal', models.IntegerField()),
                ('is_complete', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('date_completed', models.DateTimeField(default=None, null=True)),
                ('parent_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.List')),
            ],
        ),
    ]
